services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  console:
    build:
      context: ./
      dockerfile: docker/Dockerfile.console
    volumes:
      - .:/app
    depends_on:
      - app
    stdin_open: true
    tty: true

volumes:
  qdrant_data: